name: Migrate and Deploy

on:
  push:
    branches: [ main ]

jobs:
  migrate-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install Atlas CLI
        run: go install ariga.io/atlas/cmd/atlas@latest

      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          ATLAS_DEV_URL: ${{ secrets.z }}
        run: atlas migrate apply --env local

      - name: Trigger Vercel deploy (optional)
        if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != '' }}
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: curl -X POST "$VERCEL_DEPLOY_HOOK_URL"
